name: Build Audit Goggles Tool

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read version.json
      id: version
      run: |
        $json = Get-Content 'Tools\\Audit Goggles\\version.json' | ConvertFrom-Json
        echo "MAJOR=$($json.major)" >> $env:GITHUB_ENV
        echo "MINOR=$($json.minor)" >> $env:GITHUB_ENV        
        
    - name: Generate version
      id: genver
      shell: pwsh
      run: |
        $year = (Get-Date).ToString('yy')
        $dayOfYear = (Get-Date).DayOfYear.ToString('000')
        $revision = $env:GITHUB_RUN_NUMBER
        $version = "$env:MAJOR.$env:MINOR.$year$dayOfYear.$revision"
        Write-Host "Generated version: $version"
        "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Set AssemblyInfo version
      id: setassemblyinfover
      shell: pwsh
      run: |
        $version = ${{ env.VERSIOn }}
        Get-ChildItem -Path . -Recurse -Include AssemblyInfo.cs | ForEach-Object {
        (Get-Content $_) `
          -replace 'AssemblyVersion\(".*"\)', "AssemblyVersion(`"$version`")" `
          -replace 'AssemblyFileVersion\(".*"\)', "AssemblyFileVersion(`"$version`")" `
          -replace 'AssemblyInformationalVersion\(".*"\)', "AssemblyInformationalVersion(`"$version`")" `
          | Set-Content $_
        }

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore Tools/Tools.sln

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2      

    - name: Build
      run: msbuild Tools/Tools.sln /p:Configuration=Release
   
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name:  Formula81.XrmToolBox.Tools.AuditGoggles.${{ env.VERSION }}
        path: 'Tools\\Audit Goggles\\bin\\Release\\Formula81*.dll'
